package v1

import (
	controller "github.com/rancher/norman/controller"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertmanagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Client) DeepCopyInto(out *Client) {
	*out = *in
	out.Mutex = in.Mutex
	if in.restClient != nil {
		out.restClient = in.restClient.DeepCopyInterface()
	}
	if in.starters != nil {
		in, out := &in.starters, &out.starters
		*out = make([]controller.Starter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = (*in)[i].DeepCopyStarter()
			}
		}
	}
	if in.prometheusControllers != nil {
		in, out := &in.prometheusControllers, &out.prometheusControllers
		*out = make(map[string]PrometheusController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyPrometheusController()
			}
		}
	}
	if in.alertmanagerControllers != nil {
		in, out := &in.alertmanagerControllers, &out.alertmanagerControllers
		*out = make(map[string]AlertmanagerController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyAlertmanagerController()
			}
		}
	}
	if in.prometheusRuleControllers != nil {
		in, out := &in.prometheusRuleControllers, &out.prometheusRuleControllers
		*out = make(map[string]PrometheusRuleController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyPrometheusRuleController()
			}
		}
	}
	if in.serviceMonitorControllers != nil {
		in, out := &in.serviceMonitorControllers, &out.serviceMonitorControllers
		*out = make(map[string]ServiceMonitorController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyServiceMonitorController()
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Client.
func (in *Client) DeepCopy() *Client {
	if in == nil {
		return nil
	}
	out := new(Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrometheusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrometheusRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
