package v1

import (
	controller "github.com/rancher/norman/controller"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Client) DeepCopyInto(out *Client) {
	*out = *in
	out.Mutex = in.Mutex
	if in.restClient != nil {
		out.restClient = in.restClient.DeepCopyInterface()
	}
	if in.starters != nil {
		in, out := &in.starters, &out.starters
		*out = make([]controller.Starter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = (*in)[i].DeepCopyStarter()
			}
		}
	}
	if in.clusterRoleBindingControllers != nil {
		in, out := &in.clusterRoleBindingControllers, &out.clusterRoleBindingControllers
		*out = make(map[string]ClusterRoleBindingController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyClusterRoleBindingController()
			}
		}
	}
	if in.clusterRoleControllers != nil {
		in, out := &in.clusterRoleControllers, &out.clusterRoleControllers
		*out = make(map[string]ClusterRoleController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyClusterRoleController()
			}
		}
	}
	if in.roleBindingControllers != nil {
		in, out := &in.roleBindingControllers, &out.roleBindingControllers
		*out = make(map[string]RoleBindingController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyRoleBindingController()
			}
		}
	}
	if in.roleControllers != nil {
		in, out := &in.roleControllers, &out.roleControllers
		*out = make(map[string]RoleController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyRoleController()
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Client.
func (in *Client) DeepCopy() *Client {
	if in == nil {
		return nil
	}
	out := new(Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
