package v1

import (
	controller "github.com/rancher/norman/controller"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Client) DeepCopyInto(out *Client) {
	*out = *in
	out.Mutex = in.Mutex
	if in.restClient != nil {
		out.restClient = in.restClient.DeepCopyInterface()
	}
	if in.starters != nil {
		in, out := &in.starters, &out.starters
		*out = make([]controller.Starter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = (*in)[i].DeepCopyStarter()
			}
		}
	}
	if in.deploymentControllers != nil {
		in, out := &in.deploymentControllers, &out.deploymentControllers
		*out = make(map[string]DeploymentController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyDeploymentController()
			}
		}
	}
	if in.daemonSetControllers != nil {
		in, out := &in.daemonSetControllers, &out.daemonSetControllers
		*out = make(map[string]DaemonSetController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyDaemonSetController()
			}
		}
	}
	if in.statefulSetControllers != nil {
		in, out := &in.statefulSetControllers, &out.statefulSetControllers
		*out = make(map[string]StatefulSetController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyStatefulSetController()
			}
		}
	}
	if in.replicaSetControllers != nil {
		in, out := &in.replicaSetControllers, &out.replicaSetControllers
		*out = make(map[string]ReplicaSetController, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyReplicaSetController()
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Client.
func (in *Client) DeepCopy() *Client {
	if in == nil {
		return nil
	}
	out := new(Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DaemonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplicaSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
